Repository brain-tec/project, pull requests merged in 2022-11, with the labels that each got.

#571 [t132760][AKAG] Migrate and Install on Test : OCA project_task_add_very_high
  project_task_add_very_high/README.rst
  project_task_add_very_high/__init__.py
  project_task_add_very_high/__manifest__.py
  project_task_add_very_high/hooks.py
  project_task_add_very_high/i18n/ar.po
  project_task_add_very_high/i18n/ca.po
  project_task_add_very_high/i18n/cs_CZ.po
  project_task_add_very_high/i18n/de.po
  project_task_add_very_high/i18n/el.po
  project_task_add_very_high/i18n/es.po
  project_task_add_very_high/i18n/es_AR.po
  project_task_add_very_high/i18n/es_CO.po
  project_task_add_very_high/i18n/es_CR.po
  project_task_add_very_high/i18n/es_MX.po
  project_task_add_very_high/i18n/es_VE.po
  project_task_add_very_high/i18n/fi.po
  project_task_add_very_high/i18n/fr.po
  project_task_add_very_high/i18n/fr_FR.po
  project_task_add_very_high/i18n/gl.po
  project_task_add_very_high/i18n/hr.po
  project_task_add_very_high/i18n/hr_HR.po
  project_task_add_very_high/i18n/hu.po
  project_task_add_very_high/i18n/it.po
  project_task_add_very_high/i18n/ja.po
  project_task_add_very_high/i18n/lt.po
  project_task_add_very_high/i18n/lv.po
  project_task_add_very_high/i18n/mk.po
  project_task_add_very_high/i18n/mn.po
  project_task_add_very_high/i18n/nb.po
  project_task_add_very_high/i18n/nl.po
  project_task_add_very_high/i18n/nl_NL.po
  project_task_add_very_high/i18n/pl.po
  project_task_add_very_high/i18n/project_task_add_very_high.pot
  project_task_add_very_high/i18n/pt.po
  project_task_add_very_high/i18n/pt_BR.po
  project_task_add_very_high/i18n/pt_PT.po
  project_task_add_very_high/i18n/ro.po
  project_task_add_very_high/i18n/sl.po
  project_task_add_very_high/i18n/sv.po
  project_task_add_very_high/i18n/tr.po
  project_task_add_very_high/i18n/uk.po
  project_task_add_very_high/i18n/zh_CN.po
  project_task_add_very_high/models/__init__.py
  project_task_add_very_high/models/project_task.py
  project_task_add_very_high/readme/CONTRIBUTORS.rst
  project_task_add_very_high/readme/DESCRIPTION.rst
  project_task_add_very_high/readme/USAGE.rst
  project_task_add_very_high/static/description/icon.png
  project_task_add_very_high/static/description/image.png
  project_task_add_very_high/static/description/image2.png
  project_task_add_very_high/static/description/image2_a.png
  project_task_add_very_high/static/description/image_a.png
  project_task_add_very_high/static/description/index.html
  project_task_add_very_high/views/project_task_view.xml
  setup/project_task_add_very_high/odoo/addons/project_task_add_very_high
  setup/project_task_add_very_high/setup.py
Labels: 16.0.project_ak_662

#572 Syncing from upstream OCA/project (13.0)
  README.md
  project_stock/__manifest__.py
  project_stock/models/project_task.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
Labels: 13.0

#573 Syncing from upstream OCA/project (14.0)
  README.md
  project_stock/__manifest__.py
  project_stock/models/project_task.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
Labels: 14.0

#574 Syncing from upstream OCA/project (15.0)
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  README.md
  project_task_personal_stage_auto_fold/__manifest__.py
  project_task_personal_stage_auto_fold/tests/test_personal_stages.py
Labels: 15.0

#575 Renaming of priorities.
  project_task_add_very_high/models/project_task.py
Labels: 16.0.project_ak_662

#576 Syncing from upstream OCA/project (12.0)
  project_description/i18n/fr.po
Labels: 12.0

#577 Syncing from upstream OCA/project (14.0)
  project_stock/migrations/13.0.2.0.0/post-migration.py
Labels: 14.0

#578 Syncing from upstream OCA/project (15.0)
  README.md
  project_role/__manifest__.py
  project_role/models/project_role.py
  project_type/__manifest__.py
  project_type/models/project_type.py
Labels: 15.0

#579 Syncing from upstream OCA/project (16.0)
  project_template/i18n/de.po
Labels: 16.0

#580 Syncing from upstream OCA/project (14.0)
  README.md
  project_stage_mgmt/README.rst
  project_stage_mgmt/__init__.py
  project_stage_mgmt/__manifest__.py
  project_stage_mgmt/i18n/project_stage_mgmt.pot
  project_stage_mgmt/readme/CONTRIBUTORS.rst
  project_stage_mgmt/readme/DESCRIPTION.rst
  project_stage_mgmt/static/description/icon.png
  project_stage_mgmt/static/description/index.html
  project_stage_mgmt/views/project.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/project_stage_mgmt/odoo/addons/project_stage_mgmt
  setup/project_stage_mgmt/setup.py
Labels: 14.0

#581 Syncing from upstream OCA/project (15.0)
  README.md
  project_stock/README.rst
  project_stock/__init__.py
  project_stock/__manifest__.py
  project_stock/demo/project_data.xml
  project_stock/demo/stock_picking_type_data.xml
  project_stock/i18n/es.po
  project_stock/i18n/hr.po
  project_stock/i18n/it.po
  project_stock/i18n/project_stock.pot
  project_stock/migrations/15.0.1.0.0/pre-migration.py
  project_stock/models/__init__.py
  project_stock/models/account_analytic_line.py
  project_stock/models/project_project.py
  project_stock/models/project_task.py
  project_stock/models/stock_move.py
  project_stock/models/stock_scrap.py
  project_stock/readme/CONFIGURE.rst
  project_stock/readme/CONTRIBUTORS.rst
  project_stock/readme/DESCRIPTION.rst
  project_stock/readme/USAGE.rst
  project_stock/static/description/icon.png
  project_stock/static/description/index.html
  project_stock/tests/__init__.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
  project_stock/views/project_project_view.xml
  project_stock/views/project_task_type_view.xml
  project_stock/views/project_task_view.xml
  project_stock/views/stock_move_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/project_stock/odoo/addons/project_stock
  setup/project_stock/setup.py
Labels: 15.0

#583 Syncing from upstream OCA/project (15.0)
  README.md
  project_forecast_line/__manifest__.py
  project_forecast_line/models/forecast_line.py
  project_forecast_line/models/project_project.py
  project_forecast_line/models/project_task.py
  project_forecast_line/models/sale_order_line.py
  project_forecast_line/utils.py
  project_forecast_line/views/forecast_line_views.xml
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
  project_stock_product_set/README.rst
  project_stock_product_set/__init__.py
  project_stock_product_set/__manifest__.py
  project_stock_product_set/i18n/es.po
  project_stock_product_set/i18n/it.po
  project_stock_product_set/i18n/project_stock_product_set.pot
  project_stock_product_set/models/__init__.py
  project_stock_product_set/models/product_set_line.py
  project_stock_product_set/readme/CONFIGURE.rst
  project_stock_product_set/readme/CONTRIBUTORS.rst
  project_stock_product_set/readme/DESCRIPTION.rst
  project_stock_product_set/readme/USAGE.rst
  project_stock_product_set/security/ir.model.access.csv
  project_stock_product_set/static/description/icon.png
  project_stock_product_set/static/description/index.html
  project_stock_product_set/tests/__init__.py
  project_stock_product_set/tests/test_project_stock_product_set.py
  project_stock_product_set/views/project_task_view.xml
  project_stock_product_set/wizard/__init__.py
  project_stock_product_set/wizard/product_set_add.py
  project_stock_product_set/wizard/product_set_add.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/project_stock_product_set/odoo/addons/project_stock_product_set
  setup/project_stock_product_set/setup.py
Labels: 15.0

#585 Syncing from upstream OCA/project (13.0)
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  project_task_digitized_signature/README.rst
  project_task_digitized_signature/__init__.py
  project_task_digitized_signature/__manifest__.py
  project_task_digitized_signature/i18n/ar.po
  project_task_digitized_signature/i18n/ca.po
  project_task_digitized_signature/i18n/de.po
  project_task_digitized_signature/i18n/el.po
  project_task_digitized_signature/i18n/es.po
  project_task_digitized_signature/i18n/es_CR.po
  project_task_digitized_signature/i18n/es_MX.po
  project_task_digitized_signature/i18n/es_VE.po
  project_task_digitized_signature/i18n/fi.po
  project_task_digitized_signature/i18n/fr.po
  project_task_digitized_signature/i18n/gl.po
  project_task_digitized_signature/i18n/hr.po
  project_task_digitized_signature/i18n/hr_HR.po
  project_task_digitized_signature/i18n/hu.po
  project_task_digitized_signature/i18n/it.po
  project_task_digitized_signature/i18n/ja.po
  project_task_digitized_signature/i18n/lt.po
  project_task_digitized_signature/i18n/lv.po
  project_task_digitized_signature/i18n/mk.po
  project_task_digitized_signature/i18n/mn.po
  project_task_digitized_signature/i18n/nl.po
  project_task_digitized_signature/i18n/pl.po
  project_task_digitized_signature/i18n/project_task_digitized_signature.pot
  project_task_digitized_signature/i18n/pt.po
  project_task_digitized_signature/i18n/pt_BR.po
  project_task_digitized_signature/i18n/pt_PT.po
  project_task_digitized_signature/i18n/ro.po
  project_task_digitized_signature/i18n/sl.po
  project_task_digitized_signature/i18n/sv.po
  project_task_digitized_signature/i18n/tr.po
  project_task_digitized_signature/i18n/uk.po
  project_task_digitized_signature/i18n/zh_CN.po
  project_task_digitized_signature/models/__init__.py
  project_task_digitized_signature/models/project.py
  project_task_digitized_signature/readme/CONTRIBUTORS.rst
  project_task_digitized_signature/readme/DESCRIPTION.rst
  project_task_digitized_signature/readme/INSTALL.rst
  project_task_digitized_signature/readme/ROADMAP.rst
  project_task_digitized_signature/readme/USAGE.rst
  project_task_digitized_signature/report/project_task_report.xml
  project_task_digitized_signature/static/description/icon.png
  project_task_digitized_signature/static/description/index.html
  project_task_digitized_signature/tests/__init__.py
  project_task_digitized_signature/tests/test_project_task_digitized_signature.py
  project_task_digitized_signature/views/project_task_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/project_task_digitized_signature/odoo/addons/project_task_digitized_signature
  setup/project_task_digitized_signature/setup.py
Labels: 13.0

#586 Syncing from upstream OCA/project (14.0)
  .copier-answers.yml
  .pre-commit-config.yaml
  README.md
  project_task_digitized_signature/README.rst
  project_task_digitized_signature/__init__.py
  project_task_digitized_signature/__manifest__.py
  project_task_digitized_signature/i18n/ar.po
  project_task_digitized_signature/i18n/ca.po
  project_task_digitized_signature/i18n/de.po
  project_task_digitized_signature/i18n/el.po
  project_task_digitized_signature/i18n/es.po
  project_task_digitized_signature/i18n/es_CR.po
  project_task_digitized_signature/i18n/es_MX.po
  project_task_digitized_signature/i18n/es_VE.po
  project_task_digitized_signature/i18n/fi.po
  project_task_digitized_signature/i18n/fr.po
  project_task_digitized_signature/i18n/gl.po
  project_task_digitized_signature/i18n/hr.po
  project_task_digitized_signature/i18n/hr_HR.po
  project_task_digitized_signature/i18n/hu.po
  project_task_digitized_signature/i18n/it.po
  project_task_digitized_signature/i18n/ja.po
  project_task_digitized_signature/i18n/lt.po
  project_task_digitized_signature/i18n/lv.po
  project_task_digitized_signature/i18n/mk.po
  project_task_digitized_signature/i18n/mn.po
  project_task_digitized_signature/i18n/nl.po
  project_task_digitized_signature/i18n/pl.po
  project_task_digitized_signature/i18n/project_task_digitized_signature.pot
  project_task_digitized_signature/i18n/pt.po
  project_task_digitized_signature/i18n/pt_BR.po
  project_task_digitized_signature/i18n/pt_PT.po
  project_task_digitized_signature/i18n/ro.po
  project_task_digitized_signature/i18n/sl.po
  project_task_digitized_signature/i18n/sv.po
  project_task_digitized_signature/i18n/tr.po
  project_task_digitized_signature/i18n/uk.po
  project_task_digitized_signature/i18n/zh_CN.po
  project_task_digitized_signature/models/__init__.py
  project_task_digitized_signature/models/project.py
  project_task_digitized_signature/readme/CONTRIBUTORS.rst
  project_task_digitized_signature/readme/DESCRIPTION.rst
  project_task_digitized_signature/readme/INSTALL.rst
  project_task_digitized_signature/readme/ROADMAP.rst
  project_task_digitized_signature/readme/USAGE.rst
  project_task_digitized_signature/report/project_task_report.xml
  project_task_digitized_signature/static/description/icon.png
  project_task_digitized_signature/static/description/index.html
  project_task_digitized_signature/tests/__init__.py
  project_task_digitized_signature/tests/test_project_task_digitized_signature.py
  project_task_digitized_signature/views/project_task_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/project_task_digitized_signature/odoo/addons/project_task_digitized_signature
  setup/project_task_digitized_signature/setup.py
Labels: 14.0

#588 Syncing from upstream OCA/project (15.0)
  README.md
  project_task_personal_stage_auto_fold/README.rst
  project_task_personal_stage_auto_fold/__manifest__.py
  project_task_personal_stage_auto_fold/readme/CONFIGURE.rst
  project_task_personal_stage_auto_fold/readme/DESCRIPTION.rst
  project_task_personal_stage_auto_fold/readme/USAGE.rst
  project_task_personal_stage_auto_fold/static/description/index.html
Labels: 15.0

#589 Syncing from upstream OCA/project (13.0)
  README.md
  project_timesheet_time_control_sale/README.rst
  project_timesheet_time_control_sale/__init__.py
  project_timesheet_time_control_sale/__manifest__.py
  project_timesheet_time_control_sale/i18n/project_timesheet_time_control_sale.pot
  project_timesheet_time_control_sale/models/__init__.py
  project_timesheet_time_control_sale/models/account_move_line.py
  project_timesheet_time_control_sale/readme/CONTRIBUTORS.rst
  project_timesheet_time_control_sale/readme/DESCRIPTION.rst
  project_timesheet_time_control_sale/static/description/icon.png
  project_timesheet_time_control_sale/static/description/icon.svg
  project_timesheet_time_control_sale/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/project_timesheet_time_control_sale/.eggs/README.txt
  setup/project_timesheet_time_control_sale/odoo/addons/project_timesheet_time_control_sale
  setup/project_timesheet_time_control_sale/setup.py
Labels: 13.0

#590 Syncing from upstream OCA/project (14.0)
  project_tag/README.rst
  project_tag/__manifest__.py
  project_tag/i18n/de.po
  project_tag/i18n/es_AR.po
  project_tag/i18n/fr.po
  project_tag/i18n/fr_FR.po
  project_tag/i18n/he.po
  project_tag/i18n/it.po
  project_tag/i18n/project_tag.pot
  project_tag/models/__init__.py
  project_tag/models/project.py
  project_tag/models/project_task.py
  project_tag/readme/CONTRIBUTORS.rst
  project_tag/readme/USAGE.rst
  project_tag/static/description/index.html
  project_tag/views/project.xml
  project_tag/views/project_task.xml
Labels: 14.0

#591 Syncing from upstream OCA/project (14.0)
  project_tag/i18n/es_AR.po
Labels: 14.0

#592 Syncing from upstream OCA/project (15.0)
  project_timesheet_time_control/i18n/es_AR.po
Labels: 15.0
