Repository brain-tec/project, pull requests merged in 2022-04, with the labels that each got.

#486 Syncing from upstream OCA/project (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
  project_role/models/project_role.py
Labels: 14.0

#487 Syncing from upstream OCA/project (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
Labels: 15.0

#488 Syncing from upstream OCA/project (15.0)
  README.md
  project_parent_task_filter/__manifest__.py
  project_parent_task_filter/models/project_task.py
Labels: 15.0

#489 Syncing from upstream OCA/project (15.0)
  README.md
  project_task_code/README.rst
  project_task_code/__init__.py
  project_task_code/__manifest__.py
  project_task_code/data/task_sequence.xml
  project_task_code/hooks.py
  project_task_code/i18n/ar.po
  project_task_code/i18n/bg.po
  project_task_code/i18n/ca.po
  project_task_code/i18n/de.po
  project_task_code/i18n/el.po
  project_task_code/i18n/en.po
  project_task_code/i18n/es.po
  project_task_code/i18n/es_AR.po
  project_task_code/i18n/es_CR.po
  project_task_code/i18n/es_MX.po
  project_task_code/i18n/es_VE.po
  project_task_code/i18n/fi.po
  project_task_code/i18n/fr.po
  project_task_code/i18n/fr_FR.po
  project_task_code/i18n/gl.po
  project_task_code/i18n/hr.po
  project_task_code/i18n/hr_HR.po
  project_task_code/i18n/hu.po
  project_task_code/i18n/it.po
  project_task_code/i18n/ja.po
  project_task_code/i18n/lt.po
  project_task_code/i18n/lv.po
  project_task_code/i18n/mk.po
  project_task_code/i18n/mn.po
  project_task_code/i18n/nl.po
  project_task_code/i18n/nl_NL.po
  project_task_code/i18n/pl.po
  project_task_code/i18n/project_task_code.pot
  project_task_code/i18n/pt.po
  project_task_code/i18n/pt_BR.po
  project_task_code/i18n/pt_PT.po
  project_task_code/i18n/ro.po
  project_task_code/i18n/sk.po
  project_task_code/i18n/sl.po
  project_task_code/i18n/sv.po
  project_task_code/i18n/tr.po
  project_task_code/i18n/uk.po
  project_task_code/i18n/zh_CN.po
  project_task_code/models/__init__.py
  project_task_code/models/project_task.py
  project_task_code/readme/CONFIGURE.rst
  project_task_code/readme/CONTRIBUTORS.rst
  project_task_code/readme/DESCRIPTION.rst
  project_task_code/readme/USAGE.rst
  project_task_code/static/description/icon.png
  project_task_code/static/description/index.html
  project_task_code/tests/__init__.py
  project_task_code/tests/test_project_task_code.py
  project_task_code/views/project_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/project_task_code/odoo/addons/project_task_code
  setup/project_task_code/setup.py
Labels: 15.0

#493 [t128584] Integrate migration of project_template to V15
  project_template/README.rst
  project_template/__init__.py
  project_template/__manifest__.py
  project_template/i18n/de.po
  project_template/i18n/es.po
  project_template/i18n/es_AR.po
  project_template/i18n/fr.po
  project_template/i18n/fr_FR.po
  project_template/i18n/he.po
  project_template/i18n/it.po
  project_template/i18n/project_template.pot
  project_template/i18n/pt.po
  project_template/i18n/sl.po
  project_template/i18n/sv.po
  project_template/models/__init__.py
  project_template/models/project.py
  project_template/readme/CONTRIBUTORS.rst
  project_template/readme/DESCRIPTION.rst
  project_template/readme/USAGE.rst
  project_template/static/description/icon.png
  project_template/static/description/index.html
  project_template/tests/__init__.py
  project_template/tests/test_project_template.py
  project_template/views/project.xml
  setup/project_template/odoo/addons/project_template
  setup/project_template/setup.py
Labels: 15.0.project_sy_639

#494 Syncing from upstream OCA/project (13.0)
  README.md
  project_stock/__manifest__.py
  project_stock/models/project_task.py
Labels: 13.0

#495 Syncing from upstream OCA/project (15.0)
  README.md
  project_template/README.rst
  project_template/__init__.py
  project_template/__manifest__.py
  project_template/i18n/de.po
  project_template/i18n/es.po
  project_template/i18n/es_AR.po
  project_template/i18n/fr.po
  project_template/i18n/fr_FR.po
  project_template/i18n/he.po
  project_template/i18n/it.po
  project_template/i18n/project_template.pot
  project_template/i18n/pt.po
  project_template/i18n/sl.po
  project_template/i18n/sv.po
  project_template/models/__init__.py
  project_template/models/project.py
  project_template/readme/CONTRIBUTORS.rst
  project_template/readme/DESCRIPTION.rst
  project_template/readme/USAGE.rst
  project_template/static/description/icon.png
  project_template/static/description/index.html
  project_template/tests/__init__.py
  project_template/tests/test_project_template.py
  project_template/views/project.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/project_template/odoo/addons/project_template
  setup/project_template/setup.py
Labels: 15.0

#496 Syncing from upstream OCA/project (13.0)
  project_task_pull_request/i18n/ca.po
  project_task_send_by_mail/i18n/ca.po
  project_timeline/i18n/ca.po
  project_timesheet_time_control/i18n/ca.po
Labels: 13.0

#497 Syncing from upstream OCA/project (15.0)
  project_task_code/i18n/ca.po
  project_task_pull_request/i18n/ca.po
Labels: 15.0

#498 Syncing from upstream OCA/project (13.0)
  README.md
  project_stock/__manifest__.py
  project_stock/models/project_task.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
Labels: 13.0
