Repository brain-tec/project, pull requests merged in 2022-06, with the labels that each got.

#508 Syncing from upstream OCA/project (14.0)
  README.md
  project_mail_chatter/README.rst
  project_mail_chatter/__init__.py
  project_mail_chatter/__manifest__.py
  project_mail_chatter/i18n/project_mail_chatter.pot
  project_mail_chatter/i18n/pt_BR.po
  project_mail_chatter/models/__init__.py
  project_mail_chatter/models/project.py
  project_mail_chatter/readme/CONTRIBUTORS.rst
  project_mail_chatter/readme/CREDITS.rst
  project_mail_chatter/readme/DESCRIPTION.rst
  project_mail_chatter/static/description/icon.png
  project_mail_chatter/static/description/index.html
  project_mail_chatter/views/project_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/project_mail_chatter/odoo/addons/project_mail_chatter
  setup/project_mail_chatter/setup.py
Labels: 14.0

#509 Syncing from upstream OCA/project (15.0)
  README.md
  project_list/__manifest__.py
  project_list/views/project_project.xml
Labels: 15.0

#510 [t129851] Migrate dependency module: project_department
  project_department/README.rst
  project_department/__init__.py
  project_department/__manifest__.py
  project_department/i18n/ar.po
  project_department/i18n/ca.po
  project_department/i18n/de.po
  project_department/i18n/el.po
  project_department/i18n/es.po
  project_department/i18n/es_CR.po
  project_department/i18n/es_MX.po
  project_department/i18n/es_VE.po
  project_department/i18n/fi.po
  project_department/i18n/fr.po
  project_department/i18n/gl.po
  project_department/i18n/hr.po
  project_department/i18n/hr_HR.po
  project_department/i18n/hu.po
  project_department/i18n/it.po
  project_department/i18n/ja.po
  project_department/i18n/lt.po
  project_department/i18n/lv.po
  project_department/i18n/mk.po
  project_department/i18n/mn.po
  project_department/i18n/nl.po
  project_department/i18n/nl_NL.po
  project_department/i18n/pl.po
  project_department/i18n/project_department.pot
  project_department/i18n/pt.po
  project_department/i18n/pt_BR.po
  project_department/i18n/pt_PT.po
  project_department/i18n/ro.po
  project_department/i18n/sl.po
  project_department/i18n/sv.po
  project_department/i18n/tr.po
  project_department/i18n/uk.po
  project_department/i18n/zh_CN.po
  project_department/models/__init__.py
  project_department/models/project.py
  project_department/readme/CONTRIBUTORS.rst
  project_department/readme/DESCRIPTION.rst
  project_department/static/description/icon.png
  project_department/static/description/index.html
  project_department/views/project.xml
  setup/project_department/odoo/addons/project_department
  setup/project_department/setup.py
Labels: 15.0.project_me_652

#511 Syncing from upstream OCA/project (14.0)
  README.md
  project_category/i18n/it.po
  project_stage_state/i18n/it.po
  project_task_code/i18n/it.po
  project_task_default_stage/i18n/it.po
  project_task_dependency/i18n/it.po
  project_task_material/i18n/it.po
  project_task_pull_request/README.rst
  project_task_pull_request/__manifest__.py
  project_task_pull_request/i18n/it.po
  project_task_pull_request/readme/CONTRIBUTORS.rst
  project_task_pull_request/readme/USAGE.rst
  project_task_pull_request/static/description/index.html
  project_task_pull_request/views/project_task_pull_request_view.xml
  project_template/i18n/it.po
  project_timeline/i18n/it.po
  project_timesheet_time_control/i18n/it.po
Labels: 14.0

#512 Syncing from upstream OCA/project (13.0)
  README.md
  project_stock/__manifest__.py
  project_stock/i18n/es.po
  project_stock/i18n/project_stock.pot
  project_stock/migrations/13.0.2.0.0/post-migration.py
  project_stock/models/project_task.py
  project_stock/models/stock_move.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
  project_stock/views/project_task_view.xml
Labels: 13.0
