Repository brain-tec/project, pull requests merged in 2024-07, with the labels that each got.

#1006 Syncing from upstream OCA/project (15.0)
  project_hr/migrations/15.0.1.0.0/post-migration.py
Labels: 15.0

#1007 Syncing from upstream OCA/project (16.0)
  project_type/i18n/pt_BR.po
Labels: 16.0

#1008 Syncing from upstream OCA/project (14.0)
  README.md
  project_task_note/README.rst
  project_task_note/__init__.py
  project_task_note/__manifest__.py
  project_task_note/i18n/es.po
  project_task_note/i18n/project_task_note.pot
  project_task_note/models/__init__.py
  project_task_note/models/project_task.py
  project_task_note/readme/CONTEXT.rst
  project_task_note/readme/CONTRIBUTORS.rst
  project_task_note/readme/DESCRIPTION.rst
  project_task_note/readme/USAGE.srt
  project_task_note/static/description/icon.png
  project_task_note/static/description/index.html
  project_task_note/views/project_task_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/project_task_note/odoo/addons/project_task_note
  setup/project_task_note/setup.py
Labels: 14.0

#1010 Syncing from upstream OCA/project (16.0)
  project_administrator_restricted_visibility/i18n/es.po
Labels: 16.0

#1011 Syncing from upstream OCA/project (16.0)
  README.md
  project_task_project_required/README.rst
  project_task_project_required/__init__.py
  project_task_project_required/__manifest__.py
  project_task_project_required/demo/res_company.xml
  project_task_project_required/i18n/es.po
  project_task_project_required/i18n/it.po
  project_task_project_required/i18n/project_task_project_required.pot
  project_task_project_required/i18n/pt_BR.po
  project_task_project_required/models/__init__.py
  project_task_project_required/models/project_task.py
  project_task_project_required/models/res_company.py
  project_task_project_required/models/res_config_settings.py
  project_task_project_required/readme/CONFIGURE.rst
  project_task_project_required/readme/CONTRIBUTORS.rst
  project_task_project_required/readme/DESCRIPTION.rst
  project_task_project_required/static/description/icon.png
  project_task_project_required/static/description/index.html
  project_task_project_required/tests/__init__.py
  project_task_project_required/tests/test_project_task_project_required.py
  project_task_project_required/views/project_task.xml
  project_task_project_required/views/res_config_settings_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/project_task_project_required/odoo/addons/project_task_project_required
  setup/project_task_project_required/setup.py
Labels: 16.0

#1012 Syncing from upstream OCA/project (16.0)
  project_task_project_required/i18n/pt_BR.po
Labels: 16.0

#1013 Syncing from upstream OCA/project (16.0)
  project_administrator_restricted_visibility/i18n/ca.po
  project_department/i18n/ca.po
  project_stage_extra_info/i18n/ca.po
Labels: 16.0

#1014 [t148318] Migrate - get migration of project_template
  project_template/README.rst
  project_template/__init__.py
  project_template/__manifest__.py
  project_template/i18n/de.po
  project_template/i18n/es.po
  project_template/i18n/es_AR.po
  project_template/i18n/fr.po
  project_template/i18n/fr_FR.po
  project_template/i18n/he.po
  project_template/i18n/hr.po
  project_template/i18n/it.po
  project_template/i18n/nl.po
  project_template/i18n/project_template.pot
  project_template/i18n/pt.po
  project_template/i18n/pt_BR.po
  project_template/i18n/sl.po
  project_template/i18n/sv.po
  project_template/models/__init__.py
  project_template/models/project.py
  project_template/pyproject.toml
  project_template/readme/CONTRIBUTORS.md
  project_template/readme/DESCRIPTION.md
  project_template/readme/USAGE.md
  project_template/static/description/icon.png
  project_template/static/description/index.html
  project_template/tests/__init__.py
  project_template/tests/test_project_template.py
  project_template/views/project.xml
Labels: 17.0.t148318

#1016 [t148318] 17.0 mig project template
  project_template/README.rst
  project_template/__init__.py
  project_template/__manifest__.py
  project_template/i18n/de.po
  project_template/i18n/es.po
  project_template/i18n/es_AR.po
  project_template/i18n/fr.po
  project_template/i18n/fr_FR.po
  project_template/i18n/he.po
  project_template/i18n/hr.po
  project_template/i18n/it.po
  project_template/i18n/nl.po
  project_template/i18n/project_template.pot
  project_template/i18n/pt.po
  project_template/i18n/pt_BR.po
  project_template/i18n/sl.po
  project_template/i18n/sv.po
  project_template/models/__init__.py
  project_template/models/project.py
  project_template/pyproject.toml
  project_template/readme/CONTRIBUTORS.md
  project_template/readme/DESCRIPTION.md
  project_template/readme/USAGE.md
  project_template/static/description/icon.png
  project_template/static/description/index.html
  project_template/tests/__init__.py
  project_template/tests/test_project_template.py
  project_template/views/project.xml
Labels: 17.0.t148318
