Repository brain-tec/project, pull requests merged in 2024-11, with the labels that each got.

#1064 Syncing from upstream OCA/project (17.0)
  README.md
  project_task_note/README.rst
  project_task_note/__init__.py
  project_task_note/__manifest__.py
  project_task_note/i18n/es.po
  project_task_note/i18n/it.po
  project_task_note/i18n/project_task_note.pot
  project_task_note/models/__init__.py
  project_task_note/models/project_task.py
  project_task_note/pyproject.toml
  project_task_note/readme/CONTEXT.md
  project_task_note/readme/CONTRIBUTORS.md
  project_task_note/readme/DESCRIPTION.md
  project_task_note/readme/USAGE.srt
  project_task_note/static/description/icon.png
  project_task_note/static/description/index.html
  project_task_note/views/project_task_views.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1065 Syncing from upstream OCA/project (16.0)
  project_timesheet_time_control/i18n/hr.po
Labels: 16.0

#1067 Syncing from upstream OCA/project (17.0)
  project_task_stage_state/i18n/it.po
Labels: 17.0

#1068 Syncing from upstream OCA/project (17.0)
  README.md
  project_task_pull_request/README.rst
  project_task_pull_request/__init__.py
  project_task_pull_request/__manifest__.py
  project_task_pull_request/i18n/ar.po
  project_task_pull_request/i18n/ca.po
  project_task_pull_request/i18n/de.po
  project_task_pull_request/i18n/el.po
  project_task_pull_request/i18n/es.po
  project_task_pull_request/i18n/es_AR.po
  project_task_pull_request/i18n/es_CR.po
  project_task_pull_request/i18n/es_MX.po
  project_task_pull_request/i18n/es_VE.po
  project_task_pull_request/i18n/fi.po
  project_task_pull_request/i18n/fr.po
  project_task_pull_request/i18n/gl.po
  project_task_pull_request/i18n/hr.po
  project_task_pull_request/i18n/hr_HR.po
  project_task_pull_request/i18n/hu.po
  project_task_pull_request/i18n/it.po
  project_task_pull_request/i18n/ja.po
  project_task_pull_request/i18n/lt.po
  project_task_pull_request/i18n/lv.po
  project_task_pull_request/i18n/mk.po
  project_task_pull_request/i18n/mn.po
  project_task_pull_request/i18n/nl.po
  project_task_pull_request/i18n/nl_NL.po
  project_task_pull_request/i18n/pl.po
  project_task_pull_request/i18n/project_task_pull_request.pot
  project_task_pull_request/i18n/pt.po
  project_task_pull_request/i18n/pt_BR.po
  project_task_pull_request/i18n/pt_PT.po
  project_task_pull_request/i18n/ro.po
  project_task_pull_request/i18n/sl.po
  project_task_pull_request/i18n/sv.po
  project_task_pull_request/i18n/tr.po
  project_task_pull_request/i18n/uk.po
  project_task_pull_request/i18n/zh_CN.po
  project_task_pull_request/models/__init__.py
  project_task_pull_request/models/project_project.py
  project_task_pull_request/models/project_task.py
  project_task_pull_request/pyproject.toml
  project_task_pull_request/readme/CONTRIBUTORS.md
  project_task_pull_request/readme/DESCRIPTION.md
  project_task_pull_request/readme/USAGE.md
  project_task_pull_request/static/description/icon.png
  project_task_pull_request/static/description/index.html
  project_task_pull_request/tests/__init__.py
  project_task_pull_request/tests/test_project_task_pull_request.py
  project_task_pull_request/views/project_task_pull_request_view.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1070 Syncing from upstream OCA/project (16.0)
  README.md
  project_timeline/README.rst
  project_timeline/__manifest__.py
  project_timeline/models/project_task.py
  project_timeline/static/description/index.html
Labels: 16.0

#1071 Syncing from upstream OCA/project (16.0)
  README.md
  project_scrum/i18n/it.po
  project_scrum/i18n/nl.po
  project_task_default_stage/README.rst
  project_task_default_stage/__manifest__.py
  project_task_default_stage/static/description/index.html
  project_task_default_stage/views/project_view.xml
  project_timeline/README.rst
  project_timeline/__manifest__.py
  project_timeline/static/description/index.html
  project_timeline/views/project_project_view.xml
Labels: 16.0

#1072 Syncing from upstream OCA/project (17.0)
  README.md
  project_timeline/README.rst
  project_timeline/__manifest__.py
  project_timeline/models/project_task.py
  project_timeline/static/description/index.html
  project_timeline/views/project_project_view.xml
Labels: 17.0

#1073 Syncing from upstream OCA/project (17.0)
  README.md
  sale_project_task_recurrency/README.rst
  sale_project_task_recurrency/__init__.py
  sale_project_task_recurrency/__manifest__.py
  sale_project_task_recurrency/i18n/es.po
  sale_project_task_recurrency/i18n/sale_project_task_recurrency.pot
  sale_project_task_recurrency/models/__init__.py
  sale_project_task_recurrency/models/product_template.py
  sale_project_task_recurrency/models/sale_order_line.py
  sale_project_task_recurrency/pyproject.toml
  sale_project_task_recurrency/readme/CONFIGURE.md
  sale_project_task_recurrency/readme/CONTRIBUTORS.md
  sale_project_task_recurrency/readme/DESCRIPTION.md
  sale_project_task_recurrency/readme/USAGE.md
  sale_project_task_recurrency/static/description/icon.png
  sale_project_task_recurrency/static/description/index.html
  sale_project_task_recurrency/tests/__init__.py
  sale_project_task_recurrency/tests/test_product_task_recurrency.py
  sale_project_task_recurrency/views/product_template_views.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1074 Syncing from upstream OCA/project (16.0)
  README.md
  project_timeline/README.rst
  project_timeline/__manifest__.py
  project_timeline/static/description/index.html
  project_timeline/views/project_task_view.xml
Labels: 16.0

#1075 Syncing from upstream OCA/project (17.0)
  sale_project_task_recurrency/i18n/it.po
Labels: 17.0

#1076 [MIG] project_sequence: Migration to 18.0
  project_sequence/README.rst
  project_sequence/__init__.py
  project_sequence/__manifest__.py
  project_sequence/data/ir_sequence.xml
  project_sequence/i18n/de.po
  project_sequence/i18n/es.po
  project_sequence/i18n/it.po
  project_sequence/i18n/nl.po
  project_sequence/i18n/project_sequence.pot
  project_sequence/models/__init__.py
  project_sequence/models/project_project.py
  project_sequence/pyproject.toml
  project_sequence/readme/CONFIGURE.md
  project_sequence/readme/CONTRIBUTORS.md
  project_sequence/readme/CREDITS.md
  project_sequence/readme/DESCRIPTION.md
  project_sequence/readme/USAGE.md
  project_sequence/static/description/icon.png
  project_sequence/static/description/index.html
  project_sequence/tests/__init__.py
  project_sequence/tests/test_project_sequence.py
  project_sequence/views/project_project.xml
  project_sequence/wizards/__init__.py
  project_sequence/wizards/res_config_settings.py
  project_sequence/wizards/res_config_settings_view.xml
Labels: 18.0.project_ca_772

#1078 Syncing from upstream OCA/project (16.0)
  project_scrum/i18n/it.po
Labels: 16.0
