Repository brain-tec/project, pull requests merged in 2025-04, with the labels that each got.

#1141 Sync from OCA
  README.md
  project_task_add_very_high/README.rst
  project_task_add_very_high/__init__.py
  project_task_add_very_high/__manifest__.py
  project_task_add_very_high/i18n/ar.po
  project_task_add_very_high/i18n/ca.po
  project_task_add_very_high/i18n/cs_CZ.po
  project_task_add_very_high/i18n/de.po
  project_task_add_very_high/i18n/el.po
  project_task_add_very_high/i18n/es.po
  project_task_add_very_high/i18n/es_AR.po
  project_task_add_very_high/i18n/es_CO.po
  project_task_add_very_high/i18n/es_CR.po
  project_task_add_very_high/i18n/es_MX.po
  project_task_add_very_high/i18n/es_VE.po
  project_task_add_very_high/i18n/fi.po
  project_task_add_very_high/i18n/fr.po
  project_task_add_very_high/i18n/fr_FR.po
  project_task_add_very_high/i18n/gl.po
  project_task_add_very_high/i18n/hr.po
  project_task_add_very_high/i18n/hr_HR.po
  project_task_add_very_high/i18n/hu.po
  project_task_add_very_high/i18n/it.po
  project_task_add_very_high/i18n/ja.po
  project_task_add_very_high/i18n/lt.po
  project_task_add_very_high/i18n/lv.po
  project_task_add_very_high/i18n/mk.po
  project_task_add_very_high/i18n/mn.po
  project_task_add_very_high/i18n/nb.po
  project_task_add_very_high/i18n/nl.po
  project_task_add_very_high/i18n/nl_NL.po
  project_task_add_very_high/i18n/pl.po
  project_task_add_very_high/i18n/project_task_add_very_high.pot
  project_task_add_very_high/i18n/pt.po
  project_task_add_very_high/i18n/pt_BR.po
  project_task_add_very_high/i18n/pt_PT.po
  project_task_add_very_high/i18n/ro.po
  project_task_add_very_high/i18n/sl.po
  project_task_add_very_high/i18n/sv.po
  project_task_add_very_high/i18n/tr.po
  project_task_add_very_high/i18n/uk.po
  project_task_add_very_high/i18n/zh_CN.po
  project_task_add_very_high/models/__init__.py
  project_task_add_very_high/models/project_task.py
  project_task_add_very_high/pyproject.toml
  project_task_add_very_high/readme/CONTRIBUTORS.md
  project_task_add_very_high/readme/DESCRIPTION.md
  project_task_add_very_high/readme/USAGE.md
  project_task_add_very_high/static/description/icon.png
  project_task_add_very_high/static/description/image.png
  project_task_add_very_high/static/description/image2.png
  project_task_add_very_high/static/description/image2_a.png
  project_task_add_very_high/static/description/image_a.png
  project_task_add_very_high/static/description/index.html
  project_task_add_very_high/tests/__init__.py
  project_task_add_very_high/tests/test_project_task.py
  project_task_add_very_high/views/project_task_view.xml
  setup/_metapackage/pyproject.toml
Labels: 18.0

#1142 Syncing from upstream OCA/project (17.0)
  project_group_hr_timesheet/i18n/it.po
Labels: 17.0

#1143 Syncing from upstream OCA/project (14.0)
  project_task_recurring_activity/i18n/it.po
Labels: 14.0

#1145 Syncing from upstream OCA/project (18.0)
  README.md
  project_timesheet_time_control/README.rst
  project_timesheet_time_control/__manifest__.py
  project_timesheet_time_control/readme/CONTRIBUTORS.md
  project_timesheet_time_control/static/description/index.html
  project_timesheet_time_control/views/account_analytic_line_view.xml
  project_timesheet_time_control/views/project_project_view.xml
  project_timesheet_time_control/views/project_task_view.xml
Labels: 18.0

#1146 Syncing from upstream OCA/project (17.0)
  README.md
  project_task_related/README.rst
  project_task_related/__init__.py
  project_task_related/__manifest__.py
  project_task_related/i18n/es.po
  project_task_related/i18n/project_task_related.pot
  project_task_related/models/__init__.py
  project_task_related/models/project_task.py
  project_task_related/pyproject.toml
  project_task_related/readme/CONTRIBUTORS.md
  project_task_related/readme/DESCRIPTION.md
  project_task_related/static/description/icon.png
  project_task_related/static/description/index.html
  project_task_related/tests/__init__.py
  project_task_related/tests/test_project_task_related.py
  project_task_related/views/project_task_views_related.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1147 Syncing from upstream OCA/project (17.0)
  project_task_related/i18n/it.po
Labels: 17.0

#1149 Syncing from upstream OCA/project (16.0)
  README.md
  project_task_parent_completion_blocking/README.rst
  project_task_parent_completion_blocking/__init__.py
  project_task_parent_completion_blocking/__manifest__.py
  project_task_parent_completion_blocking/i18n/es.po
  project_task_parent_completion_blocking/i18n/project_task_parent_completion_blocking.pot
  project_task_parent_completion_blocking/models/__init__.py
  project_task_parent_completion_blocking/models/project_task.py
  project_task_parent_completion_blocking/readme/CONTRIBUTORS.rst
  project_task_parent_completion_blocking/readme/DESCRIPTION.rst
  project_task_parent_completion_blocking/static/description/icon.png
  project_task_parent_completion_blocking/static/description/index.html
  project_task_parent_completion_blocking/tests/__init__.py
  project_task_parent_completion_blocking/tests/test_project_task_parent_completion_blocking.py
  project_task_parent_due_auto/i18n/it.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/project_task_parent_completion_blocking/odoo/addons/project_task_parent_completion_blocking
  setup/project_task_parent_completion_blocking/setup.py
Labels: 16.0

#1150 Syncing from upstream OCA/project (17.0)
  README.md
  project_task_related/README.rst
  project_task_related/__manifest__.py
  project_task_related/i18n/es.po
  project_task_related/i18n/it.po
  project_task_related/i18n/project_task_related.pot
  project_task_related/static/description/index.html
  project_task_related/views/project_task_views_related.xml
Labels: 17.0

#1151 Syncing from upstream OCA/project (16.0)
  project_task_parent_completion_blocking/i18n/it.po
  project_task_parent_due_auto/i18n/it.po
Labels: 16.0

#1152 Syncing from upstream OCA/project (17.0)
  README.md
  project_task_related/i18n/it.po
  project_version/README.rst
  project_version/__init__.py
  project_version/__manifest__.py
  project_version/i18n/es.po
  project_version/i18n/it.po
  project_version/i18n/project_version.pot
  project_version/models/__init__.py
  project_version/models/project_project.py
  project_version/models/project_task.py
  project_version/models/project_version.py
  project_version/pyproject.toml
  project_version/readme/CONTRIBUTORS.md
  project_version/readme/DESCRIPTION.md
  project_version/readme/USAGE.md
  project_version/security/ir.model.access.csv
  project_version/static/description/icon.png
  project_version/static/description/icon.svg
  project_version/static/description/index.html
  project_version/views/project_project_views.xml
  project_version/views/project_task_views.xml
  project_version/views/project_version_views.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1155 Syncing from upstream OCA/project (18.0)
  README.md
  project_task_note/README.rst
  project_task_note/__init__.py
  project_task_note/__manifest__.py
  project_task_note/i18n/es.po
  project_task_note/i18n/it.po
  project_task_note/i18n/project_task_note.pot
  project_task_note/models/__init__.py
  project_task_note/models/project_task.py
  project_task_note/pyproject.toml
  project_task_note/readme/CONTEXT.md
  project_task_note/readme/CONTRIBUTORS.md
  project_task_note/readme/DESCRIPTION.md
  project_task_note/readme/USAGE.srt
  project_task_note/static/description/icon.png
  project_task_note/static/description/index.html
  project_task_note/views/project_task_views.xml
  setup/_metapackage/pyproject.toml
Labels: 18.0

#1156 Syncing from upstream OCA/project (17.0)
  project_version/i18n/es.po
Labels: 17.0
